*********************************************************;
*														 ;
* 	For this activity use the sashelp.shoes.			 ;
*														 ;
* 1) Create a library called shoes to store all 		 ;
*    of the new tables. 								 ;
* 														 ;
* 2) In a new table, shoes_perc, create new columns      ;
*    to calculate the following: 						 ;								 
*	 	a) The percent of the returns compared to the    ;
* 		   sales (call the variable ROS).				 ;									 
* 		b) The percent of the inventory with respect to  ;
*		   the sales (call the variable IOS). 			 ;    									 
* 		c) Create a variable, ret_index acording to:     ;
*				If ROS <0.025, ret_index is Low.		 ;
*				If ROS is between 0.025 and 0.05,		 ;
*				ret_index is Middle.					 ;
* 				If ROS > 0.5, ret_index is high.		 ;
*		d) Create a variable, inv_index acording to:     ;
*				If IOS < 2, inv_index is Under.          ;
*				If IOS >= 2 inv_index is Over.           ;
*       e) Add a column with a code representing each    ;
*          row (clue: sub & cat)                         ;
*														 ;
* 3) Create new tables: shoes_low, shoes_middle and      ;
*	 shoes_high to store the data depending on the       ;
*    ret_inv.											 ;
*														 ;
* 4) Execute a proc freq to generate a crosstable,       ;
*    in order to know the number of product (horizontal) ;
*    by region (vertical). Use options to print just the ;
*    count of each product (do not print the percent).   ;
*														 ;
* 5) Use a proc means to generate a summary of some      ;
*    descriptive statistics by product and subsidary.    ;
*    (Use the statement class and ways. Options: delete  ;
*    the number of observations, the labels (nolabel)    ;
*    and fix 1 decimal position.                         ;
*														 ;
* 6) With a proc univariate, plot a histogram for the    ;
*    sales and return variables. (Use the statement 	 ;
*    histogram and noprint option).						 ;
* 														 ;
* 7) Suppose the shoes data correspond to the year 2020. ;
*    The marketing department is expecting an increase   ;
*    of 8% in sales for 2021. Calculate a new row for    ;
*    2021 (hint: use the output statement) Drop          ;
*    inventory and returns.							     ;
*    Store the result in a new table.		             ;
*														 ;
* 8) Create a new tabe. Take the previous table as input.;	
*    Use the lag function to calculate the percentage    ;
*	 change of sales in 2021 with respect to 2020.       ;
*    Print just the data corresponding to 2021.          ;
*														 ;
*********************************************************;
